# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Determine if integer is odd or not
#'
#' @param value    Integer value
#'
#' @return boolean of whether value is odd
#'
#' @export
cpp_is_odd <- function(value = 0L) {
    .Call(`_odder_cpp_is_odd`, value)
}

